### ISSUE TITLE
Weirdness with flipped PCB (Atreus)

### ISSUE THREAD

**Issue by mattmills** [technomancy/tmk_keyboard#13]
There are several issues I encountered. 

1. The pinouts in [this file](https://github.com/technomancy/tmk_keyboard/blob/atreus/keyboard/atreus/matrix.c#L164-L174) are completely wrong. I was able to get the top layer functioning by copy-pasting the regular layout and just reversing the order of the final numbers. 

2. Pressing Fn-Shift sometimes produces a 'q'. Expected behavior would be to do nothing, if no other keys are pressed. 

3. The layout of L2 isn't consistent with the diagrams, but appears to be consistent with what's programmed in [`keymap_common.h`](https://github.com/technomancy/tmk_keyboard/blob/atreus/keyboard/atreus/keymap_common.h#L53) .

4. This one is the real deal breaker: after an hour or so of being plugged in, the keyboard is unresponsive. 

Some of these may have been fixed already, I haven't pulled since yesterday morning. This same keyboard was fine using the stock firmware. Thoughts?

**Comment by technomancy** [comment]
I will take a look at the pinout; sorry for the mix-up there. I think I might have gotten it confused since I used to have a hand-wired Teensy-based board that was backwards, and I might have used that pinout here instead of the PCB-based one.

Problem 2 is very strange... I haven't seen anything like that myself. Would be interested in hearing if anyone else can repro.

For problem 3, which diagrams are you comparing it to? It is intended that it be different from https://atreus.technomancy.us/cheat as this is a new revision designed to make the arrow keys easier to reach, but it would probably be a good idea to note this in the readme and make the old layout available as an option.

I noticed some problems similar to 4 earlier that were traced to power-saving issues. Can you watch to see whether this happens when plugged into a laptop that is on battery power or whether the power state has no effect on it?

Thanks for the detailed report.

**Comment by mattmills** [comment]
So, #3 above seems to have been fixed just by pulling master and re-uploading; safe to assume it's fixed. #4 was on battery power, I'm using the KB this afternoon to see if it happens again, plugged into mains. As for #1 and two, still seeing them today. The q issue is pretty vexing, because any key combos that need shift and a number don't work. So I can't take screenshots, for example. Worst case scenario, the stock firmware worked fine, so I can always use that.

**Comment by technomancy** [comment]
The problem with q was just a stupid goof copying from the momentary-l2 layout; it should be fixed in the latest.

**Comment by mattmills** [comment]
Confirmed fixed with the latest from master. The crash behavior seems to be the last issue, but I've only seen it once since Friday. Going to go ahead and close this, and will open a more specific issue when I can reliably reproduce it. Thanks for the fixes!

**Comment by technomancy** [comment]
OK, cool. One other thing to watch for is whether it cuts out after a period of idleness or whether it cuts out during typing. The first would indicate a problem with power-saving.
