### ISSUE TITLE
PCBUP == PCBDOWN ?

### ISSUE THREAD

**Issue by shassard** [technomancy/tmk_keyboard#20]
Hi there,

I decided to switch to the new TMK based firmware and found that my keyboard keys have all been flipped.

It seems like I need to set PCBDOWN in OPT_DEFS as per the documentation, but it doesn't seem to do anything.

Looking at commit b6e2c476d757d70442052713912c6824f34681f7 - it seems like PCBUP and PCBDOWN are the same layouts? Perhaps I'm reading the code wrong?

**Comment by technomancy** [comment]
Stephen Hassard <notifications@github.com> writes:

> It seems like I need to set PCBDOWN in OPT_DEFS as per the
> documentation, but it doesn't seem to do anything.

Hm... it may be that it's necessary to "make clean" after changing
OPT_DEFS. I'll see if I can get it so this is not required, or at least
document it otherwise.

> Looking at commit b6e2c47 - it seems like PCBUP and PCBDOWN are the
> same layouts? Perhaps I'm reading the code wrong?

The only difference is the middle thumb keys must be flipped. But you
shouldn't use KEYMAP_PCBDOWN or KEYMAP_PCBUP directly; the KEYMAP macro
will be aliased to the correct one automatically.

**Comment by Minsekt** [comment]
hey. ive been using the old atreus-firmware before and had to flip the layout. (had to use make SWAPCOLUMNS=yes)

i get confused because you mentioned older boards have to flip the layout now with the new tmk firmware.

so the question is, if i had so flip the old firmware (atreus-firmware) do i have to flip the tmk firmware too or not ? 

thanks

**Comment by technomancy** [comment]
@Minsekt That's correct; the configuration that used to be backwards (`SWAPCOLUMNS=yes`) is now the default. So you shouldn't need to flip the TMK framework.

**Comment by Minsekt** [comment]
@technomancy sweet, thanks!

**Comment by shassard** [comment]
Commit a6d55fc02ee25be14d7dfd1a2fb7fe97a9c61a75 fixed my problem. Thanks!
